# Generated by Django 3.1.7 on 2021-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=2),
        ),
    ]
